"""
report_generator.py

PDF report generator for the Leukemia Detection API.
Builds a clinical-style PDF containing: prediction, confidence, date/time,
Grad-CAM heatmap, AI-generated (Groq) summary, and disclaimer.

No original uploaded image is included by design — /predict already
deletes the temp upload after responding, and the report is generated
later from the saved heatmap + known prediction values.

Dependencies:
    pip install reportlab pillow groq
"""

from __future__ import annotations

import io
import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import HRFlowable


# --------------------------------------------------------------------------- #
# Data model
# --------------------------------------------------------------------------- #

@dataclass
class ReportData:
    prediction_label: str                   # e.g. "Acute Lymphoblastic Leukemia (ALL)"
    confidence_score: float                  # 0-1 (e.g. 0.93) or 0-100 — handled either way
    heatmap_path: str                        # path to the saved Grad-CAM image (e.g. static/images/heatmap_xxx.jpg)
    abnormal_region_count: int = 0           # from analyze_heatmap_regions()
    ai_summary: str = ""                     # pre-generated text from generate_ai_summary()
    patient_id: Optional[str] = None
    model_name: str = "DenseNet-Leukemia"
    confidence_is_percentage: bool = False
    extra_fields: dict = field(default_factory=dict)
    report_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8].upper())
    generated_at: datetime = field(default_factory=datetime.now)
    clinic_name: str = "Leukemia Detection AI Report"


# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

DISCLAIMER_TEXT = (
    "DISCLAIMER: This report is generated by an artificial intelligence "
    "system and is intended for research and informational support purposes "
    "only. It is NOT a substitute for professional medical diagnosis, advice, "
    "or treatment. All results, including the predicted class, confidence "
    "score, and Grad-CAM visualization, must be reviewed and confirmed by a "
    "qualified, licensed hematologist or oncologist before any clinical "
    "decision is made. The model's predictions may contain errors, including "
    "false positives and false negatives, and are not a clinical diagnosis."
)


def _confidence_color(confidence_pct: float):
    if confidence_pct >= 90:
        return colors.HexColor("#1a7f37")
    if confidence_pct >= 70:
        return colors.HexColor("#9a6700")
    return colors.HexColor("#cf222e")


def _load_heatmap_image(path: str) -> PILImage.Image:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Heatmap image not found at: {path}")
    img = PILImage.open(path)
    if img.mode not in ("RGB", "L"):
        img = img.convert("RGB")
    return img


def _pil_to_reportlab_image(pil_img: PILImage.Image, max_width_mm: float, max_height_mm: float) -> Image:
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    buf.seek(0)

    orig_w, orig_h = pil_img.size
    max_w_pt = max_width_mm * mm
    max_h_pt = max_height_mm * mm
    scale = min(max_w_pt / orig_w, max_h_pt / orig_h)

    return Image(buf, width=orig_w * scale, height=orig_h * scale)


# --------------------------------------------------------------------------- #
# Main entry point
# --------------------------------------------------------------------------- #

def generate_report(data: ReportData, output_path: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(output_path)) or ".", exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=16 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        title=f"Leukemia AI Report {data.report_id}",
    )

    styles = getSampleStyleSheet()
    style_title = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=18, alignment=TA_CENTER,
        textColor=colors.HexColor("#1f2937"), spaceAfter=2,
    )
    style_subtitle = ParagraphStyle(
        "ReportSubtitle", parent=styles["Normal"], fontSize=10, alignment=TA_CENTER,
        textColor=colors.HexColor("#6b7280"), spaceAfter=10,
    )
    style_section_header = ParagraphStyle(
        "SectionHeader", parent=styles["Heading2"], fontSize=12,
        textColor=colors.HexColor("#1f2937"), spaceBefore=14, spaceAfter=6,
    )
    style_body = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=10, leading=14, alignment=TA_LEFT,
    )
    style_caption = ParagraphStyle(
        "Caption", parent=styles["Normal"], fontSize=8.5, alignment=TA_CENTER,
        textColor=colors.HexColor("#6b7280"), spaceBefore=4,
    )
    style_disclaimer = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8, leading=11,
        textColor=colors.HexColor("#6b7280"), borderColor=colors.HexColor("#d1d5db"),
        borderWidth=0.5, borderPadding=8, backColor=colors.HexColor("#f9fafb"),
    )

    confidence_pct = (
        data.confidence_score if data.confidence_is_percentage
        else data.confidence_score * 100
    )

    story = []

    # ---- Header ----
    story.append(Paragraph(data.clinic_name, style_title))
    story.append(Paragraph("Automated AI Prediction Report", style_subtitle))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#d1d5db"), thickness=0.75))
    story.append(Spacer(1, 10))

    # ---- Metadata ----
    meta_rows = [
        ["Report ID:", data.report_id, "Date / Time:", data.generated_at.strftime("%Y-%m-%d %H:%M:%S")],
        ["Patient ID:", data.patient_id or "N/A", "Model:", data.model_name],
    ]
    for k, v in data.extra_fields.items():
        meta_rows.append([f"{k}:", str(v), "", ""])

    meta_table = Table(meta_rows, colWidths=[28 * mm, 60 * mm, 28 * mm, 56 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#374151")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 6))

    # ---- Prediction result ----
    story.append(Paragraph("Prediction Result", style_section_header))

    result_table = Table(
        [["Predicted Class", "Confidence Score", "Heatmap Regions Flagged"],
         [data.prediction_label, f"{confidence_pct:.1f}%", str(data.abnormal_region_count)]],
        colWidths=[80 * mm, 46 * mm, 46 * mm],
    )
    result_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8.5),
        ("FONTSIZE", (0, 1), (0, 1), 12),
        ("FONTSIZE", (1, 1), (-1, 1), 13),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TEXTCOLOR", (1, 1), (1, 1), _confidence_color(confidence_pct)),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#d1d5db")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(result_table)
    story.append(Spacer(1, 10))

    # ---- Grad-CAM heatmap ----
    story.append(Paragraph("Grad-CAM Heatmap Visualization", style_section_header))

    heatmap_pil = _load_heatmap_image(data.heatmap_path)
    heatmap_flowable = _pil_to_reportlab_image(heatmap_pil, max_width_mm=120, max_height_mm=100)

    heatmap_table = Table(
        [[heatmap_flowable], [Paragraph(
            "Red boxes indicate regions of high model attention (Grad-CAM), "
            "flagged using the model's gradient-based activation map.",
            style_caption,
        )]],
        colWidths=[170 * mm],
    )
    heatmap_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(heatmap_table)
    story.append(Spacer(1, 10))

    # ---- AI-generated summary (Groq) ----
    story.append(Paragraph("AI-Generated Summary", style_section_header))
    story.append(Paragraph(data.ai_summary, style_body))
    story.append(Spacer(1, 14))

    # ---- Disclaimer ----
    story.append(KeepTogether([
        Paragraph("Disclaimer", style_section_header),
        Paragraph(DISCLAIMER_TEXT, style_disclaimer),
    ]))

    # ---- Footer ----
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5e7eb"), thickness=0.5))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Report generated automatically on {data.generated_at.strftime('%Y-%m-%d at %H:%M:%S')} "
        f"\u2014 Report ID {data.report_id}",
        style_caption,
    ))

    doc.build(story)
    return output_path